FROM ubuntu:20.04
#Dockerfile.ubuntu.20.04

RUN apt update &&   apt install -y  qt5-qmake cmake gcc g++ 

ENV PYTHONUNBUFFERED=1
RUN apt install -y python3 && ln -sf python3 /usr/bin/python && \
	apt-get install -y python3-pip && pip3 install --no-cache --upgrade pip setuptools  && \
	\
	# korni paxos node  \
	apt install -y libsqlite3-dev && \
	pip3 install pylint flake8 pysqlite3 asyncio pause && \
	\
	# utility build \
	apt install -y wget libboost-program-options-dev  nlohmann-json3-dev libssl-dev  && \
	cd /usr/include/boost/ && wget https://github.com/nlohmann/json/releases/download/v3.10.5/json.hpp

COPY korni3 /korni3
RUN cd /korni3 && mkdir -p /korni3/build && cd /korni3/build && rm -rf * && cmake .. && make 
